### PR TITLE
Frontend 2.0

### PR DESCRIPTION
**Pull request by Yukaii**
### TODOs

- [x] 把現階段沒用到的元件砍一砍

### CODE REVIEW

**Comment by JennyLan** [comment]
**Low priority**
- [Mobile] - Link notif - Display on Map View and Factory Detail View: Show under top caption title, on top of big title. Refer to Figma [Dev Ready 2.0]
- [All Platforms] - Text field style: Border color style should be Primary Green. Refer to Figma [Dev Ready 2.0] and [Design System 2.0] for different states.

**Comment by Yukaii** [comment]
> **Low priority**
> 
> * [Mobile] - Link notif - Display on Map View and Factory Detail View: Show under top caption title, on top of big title. Refer to Figma [Dev Ready 2.0]
> * [All Platforms] - Text field style: Border color style should be Primary Green. Refer to Figma [Dev Ready 2.0] and [Design System 2.0] for different states.

@JennyLan These two should be fixed in the latest build.

**Comment by Yukaii** [comment]
- [ ] Slide group scroll position should be reset
    disfactory-lost-scroll-position

**Comment by Yukaii** [comment]
- [ ] MInimap eats touch event: scroll on minimap would prevent scroll behavior

**Comment by Yukaii** [comment]
9C1633A8-F3BB-482E-A1C0-732DC7A79F83

iPadOS 14 跑版

**Pull request merged**
