### PR TITLE
add: popover menu for setting button sheet, close #43

### LINKED ISSUE #43: 電腦版顯示設定按鈕改用 popover menu
Screen Shot 2020-11-11 at 8 13 44 PM

### PR DESCRIPTION
**Pull request by howard-tzw**
resolve issue #43

### CODE REVIEW

**Comment by Yukaii** [comment]
Hi @howard-tzw, thank you for the contribution!

The new menu looks great! However, I still want to keep the old bottom sheet on mobile screen size. Could the new menu only show on the desktop screen? You can use Vuetify breakpoint API:

https://github.com/Disfactory/frontend/blob/4ea3e9f66b0e682909a1687db5b1ce97457fd3a5/src/components/FactoryDetailPage.vue#L67

Desktop Design: https://www.figma.com/file/nTYqE10obqYSy2x9zY6Oer/Disfactory_UI_design?node-id=494%3A7845
Mobile Design: https://www.figma.com/file/nTYqE10obqYSy2x9zY6Oer/Disfactory_UI_design?node-id=244%3A1177

**Comment by howard-tzw** [comment]
Hi @Yukaii, I updated the commit for the  button on mobile screen size, please help me review the code, thanks!

**Review by Yukaii — APPROVED** [review]
LGTM

**Comment by Yukaii** [comment]
It works pretty well! Thank you for the contribution @howard-tzw  🎉

**Pull request merged**
